# Generated by Django 2.1.7 on 2019-04-08 13:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('username', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
