# Generated by Django 2.1.7 on 2019-04-10 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitt',
            fields=[
                ('pitt_id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('audio', models.BinaryField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subs_id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='base_app.User'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='base_app.User'),
        ),
        migrations.AddField(
            model_name='pitt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.User'),
        ),
    ]
