# Generated by Django 2.1.7 on 2019-04-19 15:15

import base_app.models.pitt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitt',
            name='audio',
            field=models.FileField(upload_to=base_app.models.pitt.user_directory_path),
        ),
    ]
