# Generated by Django 2.1.7 on 2019-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitt',
            name='audio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pitt',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
