# Generated by Django 2.1.7 on 2019-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_update_pitt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitt',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
